FROM node:alpine AS build
WORKDIR /client
COPY package.json .
RUN npm config set @buf:registry https://buf.build/gen/npm/v1/
RUN npm install
COPY . .
RUN npm run build

FROM nginx
COPY --from=build /client/build /usr/share/nginx/html